Add convenience function for loading a picture directly from a file
gopxl/pixel pull request #111
Opened 2024-08-21 14:22 UTC by dusk125

2024-08-21 15:44 UTC, bhperry reviewed
Should the Atlas file helpers use this?

2024-08-21 15:47 UTC, dusk125 commented
Not directly, but I can update the atlas to mimic this functionality.

The atlas loads the images as `image.Image` so it can pack them, then creates the `pixel.PictureData` from the already loaded images.

2024-08-21 16:07 UTC, dusk125 commented
Thanks for the review, converting back to draft as I want to test something else out.

2024-08-22 04:51 UTC, bhperry commented
Alternative proposal from discord discussions:
```
type ImageLoader interface {
    Image(path string) (image.Image, error)
    PictureData(path string) (*PictureData, error)
}

func NewFileLoader(decoder DecoderFunc) FileLoader {
    if decoder == nil {
        decoder = DefaultImageDecoder
    }
    return FileLoader{decoder: decoder}
}

type FileLoader struct {
    decoder DecoderFunc
}

func (fl FileLoader) Image(path string) (image.Image, error) {
    f, err := os.Open(path)
    if err != nil {
        return nil, err
    }
    defer f.Close()

    return fl.decoder(f)
}

func (fl FileLoader) PictureData(path string) (*PictureData, error) {
    img, err := fl.Image(path)
    if err != nil {
        return nil, err
    }
    return PictureDataFromImage(img), nil
}

func NewEmbedLoader(fs fs.FS, decoder DecoderFunc) EmbedLoader {
    if decoder == nil {
        decoder = DefaultImageDecoder
    }
    return EmbedLoader{fs: fs, decoder: decoder}
}

type EmbedLoader struct {
    fs      fs.FS
    decoder DecoderFunc
}

func (el EmbedLoader) Image(path string) (image.Image, error) {
    f, err := el.fs.Open(path)
    if err != nil {
        return nil, err
    }
    defer f.Close()

    return el.decoder(f)
}

func (el EmbedLoader) PictureData(path string) (*PictureData, error) {
    img, err := el.Image(path)
    if err != nil {
        return nil, err
    }
    return PictureDataFromImage(img), nil
}
```

2024-08-31 01:23 UTC, bhperry requested changes

2024-08-31 01:23 UTC, bhperry commented on ext/atlas/help.go
> +func loadSprite(file string, decoder pixel.DecoderFunc) (i image.Image, err error) {
Seems like these should be LoadImage and LoadEmbedImage funcs in the pixel package

2024-08-31 01:23 UTC, bhperry commented on ext/atlas/group.go
>  	}
Was thinking these should return error instead of auto-panic, but if we have the `LoadImage` helpers as exported functions in pixel then I don't mind these panicing on error. The contract would be if you care about handling the image load error, do `pixel.LoadImage` followed by `atlas.AddImage`, and if not then you use `atlas.AddFile`

2024-08-31 01:37 UTC, bhperry commented on ext/atlas/help.go
> +func loadSprite(file string, decoder pixel.DecoderFunc) (i image.Image, err error) {
or I guess `ImageFromFile` and `ImageFromEmbed` to follow the same naming scheme as `PictureDataFromFile`

2024-08-31 02:18 UTC, dusk125 commented on ext/atlas/group.go
>  	}
I agree, my use-case for the atlas was to cache the textures in a var block which would be annoying without the auto-panic. But you bring a good point and someone wanting to handle the error could take that extra step

2024-08-31 02:20 UTC, bhperry commented on ext/atlas/group.go
>  	}
oh yeah it is nice that it can load to a global var, so having both options sounds perfect

2024-08-31 03:30 UTC, bhperry approved these changes

2024-08-31 20:02 UTC, merged