refactoring project
gopxl/pixel pull request #64
Opened 2023-10-11 18:48 UTC by duysqubix

Addressing  #63

2023-10-11 19:01 UTC, dusk125 requested changes

2023-10-11 19:01 UTC, dusk125 commented on backends/vulcan/.init
The graphics library is "Vulkan"

2023-10-11 19:01 UTC, dusk125 commented on backends/sdl/.init
SDL is more like Pixel than an actual rendering backend; it's built on top of OpenGL, Vulkan, and Metal. I don't know if it makes sense to include as a backend.

2023-10-11 19:01 UTC, dusk125 commented on backends/opengl/.init
Pixelgl is our opengl backend, you could move it here.

2023-10-11 19:16 UTC, duysqubix commented on go.mod
> +	github.com/gopxl/glhf/v2 v2.0.0
thank you for catching that

2023-10-12 00:57 UTC, duysqubix commented on backends/opengl/.init
yea, i still plan on doing that. I already opened a PR because I feel like this one will be pretty volatile as we decide and discuss. Rather push new changes so we can all collaborate in real-time

2023-10-12 00:58 UTC, bhperry commented
I guess let's update the readme in `ext` to call them "Extensions" now?

2023-10-12 01:04 UTC, dusk125 commented on backends/opengl/.init
Yeah fair, probably better to do the move in another PR.

2023-10-12 01:07 UTC, dusk125 commented on ext/README.md
>  ## Creating a Plugin
*cough* Extension *cough*

2023-10-12 01:10 UTC, dusk125 commented on backends/opengl/.init
remove please

2023-10-12 01:11 UTC, duysqubix commented on ext/README.md
>  ## Creating a Plugin
whoopps

2023-10-12 01:26 UTC, bhperry commented
need to change the package name pixelgl -> opengl

2023-10-12 01:28 UTC, bhperry commented on go.mod
> +	github.com/stretchr/objx v0.5.0 // indirect
where's this coming from?

2023-10-12 01:29 UTC, duysqubix commented on go.mod
> +	github.com/stretchr/objx v0.5.0 // indirect
im not sure.. but a go mod tidy cleaned that up

2023-10-12 01:31 UTC, bhperry commented on go.mod
> +	github.com/stretchr/objx v0.5.0 // indirect
Well alrighty then

2023-10-12 01:42 UTC, dusk125 approved these changes

2023-10-12 01:43 UTC, merged